language: node

sudo: required

env:
  - COMPOSE_VERSION=1.24.1

git:
  depth: 3

before_install:
  # Docker Compose Install
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  # Download and install Docker libs
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # Travis CI has its own postgres which conflicts with docker postgres
  - sudo service postgresql stop

stages:
  - name: test
  - name: build
  - name: version
    if: branch = master


jobs:
  include:
    - stage: test
      before_script: docker-compose build test
      script: docker-compose run test

    - stage: build
      before_script: docker-compose build test
      script: docker-compose run build

    - stage: version
      before_script: docker-compose build version
      script: docker-compose run version
